# Generated by Django 3.1.5 on 2021-02-13 03:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Desarrollo'),
        ),
    ]
