# Generated by Django 3.1.5 on 2021-02-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Moneda'),
        ),
    ]
