# Generated by Django 3.1.5 on 2021-02-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210215_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False, verbose_name='Moneda'),
        ),
    ]
