# Generated by Django 3.1.5 on 2021-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210215_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
