# Generated by Django 3.1.5 on 2021-02-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210218_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='active',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='staff',
        ),
    ]
