# Generated by Django 3.1.5 on 2021-02-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210218_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha última edición'),
        ),
    ]
