# Generated by Django 3.1.5 on 2021-02-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210220_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Orden'),
        ),
    ]
