# Generated by Django 3.1.5 on 2021-02-21 12:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210220_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publi',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Orden')),
                ('text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Desarrollo')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
