# Generated by Django 3.1.5 on 2021-02-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210221_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publi',
            new_name='Text',
        ),
    ]
