# Generated by Django 3.1.5 on 2021-02-21 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210221_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['order'], 'verbose_name': 'Publicidad', 'verbose_name_plural': 'Publicidades'},
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Desarrollo'),
        ),
    ]
