# Generated by Django 3.1.5 on 2021-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210221_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Título'),
        ),
    ]
