# Generated by Django 3.1.5 on 2021-02-26 03:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_text_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Orden')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Desarrollo')),
            ],
            options={
                'verbose_name': 'Plan disponible',
                'verbose_name_plural': 'Planes disponibles',
                'ordering': ['cost'],
            },
        ),
    ]
