# Generated by Django 3.1.5 on 2021-02-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=False, verbose_name='Mostrar')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Red social')),
                ('link', models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='Link')),
            ],
        ),
    ]
