# Generated by Django 3.1.5 on 2021-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['initial'], 'verbose_name': 'Plan disponible', 'verbose_name_plural': 'Planes disponibles'},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='cost',
            new_name='initial',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='text',
        ),
        migrations.AddField(
            model_name='plan',
            name='six',
            field=models.IntegerField(blank=True, null=True, verbose_name='6 meses'),
        ),
        migrations.AddField(
            model_name='plan',
            name='three',
            field=models.IntegerField(blank=True, null=True, verbose_name='3 meses'),
        ),
        migrations.AddField(
            model_name='plan',
            name='twelve',
            field=models.IntegerField(blank=True, null=True, verbose_name='12 meses'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Red social'),
        ),
    ]
