# Generated by Django 3.1.5 on 2021-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210226_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='invertion',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Precio'),
        ),
    ]
