# Generated by Django 3.1.5 on 2021-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210226_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paybutton',
            field=models.BooleanField(default=False, verbose_name='Botón de pago'),
        ),
        migrations.AddField(
            model_name='plan',
            name='urlbutton',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='Link Paypal'),
        ),
    ]
