# Generated by Django 3.1.5 on 2021-02-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210226_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Nº Meses')),
                ('title', models.CharField(max_length=200, verbose_name='Meses')),
            ],
            options={
                'verbose_name_plural': 'Meses',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['id'], 'verbose_name': 'Plan disponible', 'verbose_name_plural': 'Planes disponibles'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='invertion',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Inversión total'),
        ),
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.month', verbose_name='Meses'),
        ),
    ]
