# Generated by Django 3.1.5 on 2021-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210226_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['title'], 'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
        migrations.AddField(
            model_name='text',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Link a youtube'),
        ),
    ]
