# Generated by Django 3.1.5 on 2021-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210226_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['id'], 'verbose_name_plural': 'Costos planes'},
        ),
        migrations.RemoveField(
            model_name='pay',
            name='payment',
        ),
        migrations.AddField(
            model_name='pay',
            name='title',
            field=models.CharField(default='sin especificar', max_length=200, verbose_name='Costo (texto)'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Costo en euros'),
        ),
    ]
