# Generated by Django 3.1.5 on 2021-02-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210226_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='title',
        ),
    ]
