# Generated by Django 3.1.5 on 2021-02-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_pay_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tiempo en meses'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['id'], 'verbose_name_plural': 'Costo de plan'},
        ),
        migrations.RemoveField(
            model_name='month',
            name='title',
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Tiempo en meses'),
        ),
    ]
