# Generated by Django 3.1.5 on 2021-02-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210226_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
