# Generated by Django 3.1.5 on 2021-02-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_month_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tiempo en meses'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['name'], 'verbose_name_plural': 'Costo de plan'},
        ),
        migrations.RemoveField(
            model_name='month',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='id',
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Tiempo en meses'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='name',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Costo en euros'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
