# Generated by Django 3.1.5 on 2021-02-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210226_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['name'], 'verbose_name': 'Costo', 'verbose_name_plural': 'Costos de planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Plan activo'),
        ),
    ]
