# Generated by Django 3.1.5 on 2021-02-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210226_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='tag',
            field=models.CharField(default='<i class="fas fa-redo"></i>', max_length=100, verbose_name='Ícono class='),
        ),
    ]
