# Generated by Django 3.1.5 on 2021-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210227_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='Link sitio'),
        ),
        migrations.AlterField(
            model_name='social',
            name='tag',
            field=models.CharField(default='fas fa-redo', max_length=100, verbose_name='Ícono class='),
        ),
    ]
