# Generated by Django 3.1.5 on 2021-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_plan_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses (3,6 o 12)'),
        ),
    ]
