# Generated by Django 3.1.5 on 2021-03-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210303_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default=2, max_length=200, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
