# Generated by Django 3.1.5 on 2021-02-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link',
            new_name='wallet',
        ),
        migrations.AddField(
            model_name='profile',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
