# Generated by Django 3.1.5 on 2021-02-12 13:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210211_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', ckeditor.fields.RichTextField(max_length=200, verbose_name='Desarrollo')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['balance']},
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='since',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
