# Generated by Django 3.1.5 on 2021-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210212_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['balance'], 'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['updated'], 'verbose_name': 'Pregunta frecuente'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['created'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
