# Generated by Django 3.1.5 on 2021-02-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210212_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
