# Generated by Django 3.1.5 on 2021-02-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210214_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de contrato'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Dinero invertido en euros'),
        ),
    ]
