# Generated by Django 3.1.5 on 2021-02-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20210215_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
