# Generated by Django 3.1.5 on 2021-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20210218_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='seebutton',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
