# Generated by Django 3.1.5 on 2021-02-18 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0018_auto_20210218_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='seebutton',
            new_name='paybutton',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
