# Generated by Django 3.1.5 on 2021-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20210218_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='active',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='staff',
        ),
        migrations.AddField(
            model_name='seller',
            name='fisrt_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Dinero invertido'),
        ),
    ]
