# Generated by Django 3.1.5 on 2021-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20210218_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
