# Generated by Django 3.1.5 on 2021-02-20 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0023_auto_20210218_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='fisrt_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días contrato'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario'),
        ),
    ]
