# Generated by Django 3.1.5 on 2021-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20210220_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
