# Generated by Django 3.1.5 on 2021-02-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_seller_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='active',
            new_name='client_active',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='active',
            new_name='seller_active',
        ),
    ]
