# Generated by Django 3.1.5 on 2021-02-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20210221_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='client_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_active',
            new_name='active',
        ),
    ]
