# Generated by Django 3.1.5 on 2021-02-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210226_1544'),
        ('registration', '0029_auto_20210226_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='Plan elegido'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='currencys',
        ),
        migrations.AddField(
            model_name='profile',
            name='currencys',
            field=models.ManyToManyField(blank=True, null=True, to='core.Currency', verbose_name='Moneda elegida '),
        ),
    ]
