# Generated by Django 3.1.5 on 2021-02-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20210226_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
    ]
