# Generated by Django 3.1.5 on 2021-02-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20210226_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paybutton',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='urlbutton',
        ),
    ]
