# Generated by Django 3.1.5 on 2021-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_auto_20210226_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gain',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganancia acumulada'),
        ),
    ]
