# Generated by Django 3.1.5 on 2021-02-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_auto_20210226_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet',
        ),
    ]
