# Generated by Django 3.1.5 on 2021-02-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210227_0249'),
        ('registration', '0036_profile_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currencys',
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Plan elegido'),
        ),
    ]
