# Generated by Django 3.1.5 on 2021-02-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_auto_20210227_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['seller'], 'verbose_name': 'Perfil Cliente', 'verbose_name_plural': 'Perfiles de Clientes'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='days',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='money',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gain',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ganancia'),
        ),
    ]
