# Generated by Django 3.1.5 on 2021-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210227_0249'),
        ('registration', '0040_auto_20210227_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.ManyToManyField(to='core.Currency', verbose_name='Monedas'),
        ),
    ]
