# Generated by Django 3.1.5 on 2021-02-27 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210227_0249'),
        ('registration', '0042_auto_20210227_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Moneda principal'),
        ),
    ]
