# Generated by Django 3.1.5 on 2021-03-02 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210227_0249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0043_auto_20210227_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='Plan elegido'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.seller', verbose_name='Vendedor asignado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
