# Generated by Django 3.1.5 on 2021-03-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210227_0249'),
        ('registration', '0044_auto_20210301_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='Plan elegido'),
        ),
    ]
