# Generated by Django 3.1.5 on 2021-03-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_auto_20210302_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
    ]
