# Generated by Django 3.1.5 on 2021-03-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_plan_active'),
        ('registration', '0047_auto_20210303_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='Plan elegido'),
        ),
    ]
