# Generated by Django 3.1.5 on 2021-03-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20210303_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.seller', verbose_name='Vendedor asignado'),
        ),
    ]
