# Generated by Django 3.1.5 on 2021-03-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210307_1829'),
        ('registration', '0050_auto_20210306_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Moneda principal'),
        ),
    ]
